# Input/output configuration
input_dir: /data/jduarte1/train_1/
output_dir: /data/jduarte1/train_1_hitgraphs/raw/
n_files: 1770

# Graph building configuration
selection:
    pt_min: 1 # GeV
    phi_slope_max: 99999
    z0_max: 99999
    n_tracks: 10
    no_missing_hits: True
    n_phi_sections: 8
    n_eta_sections: 1
    eta_range: [-999, 999]
